# Generated by Django 5.0.3 on 2024-03-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_updated',
            field=models.BooleanField(default=False, help_text='This attribute designates whether this user has updated requirements for an account. User should update account details before using the app', verbose_name='updated'),
        ),
    ]
