# Generated by Django 5.0.3 on 2024-03-20 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_useraccount_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pix',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='profile image'),
        ),
    ]
