# Generated by Django 5.0.3 on 2024-03-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transaction_ref', models.CharField(max_length=100)),
                ('payment_note', models.CharField(blank=True, max_length=250, null=True)),
                ('Transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=200)),
                ('Initiator_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=200)),
                ('Receiver_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
