# Generated by Django 5.0.3 on 2024-03-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='Payer_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
