# Generated by Django 5.0.3 on 2024-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_paymentrequest_payer_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_note',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
