# Generated by Django 5.0.3 on 2024-04-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_alter_paymentrequest_payment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='Transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=200),
        ),
    ]
